services:

  principal:
    build:
      context: .
    volumes:
      - ../output:/output
      - ../tex:/tex
      - ./build:/build
    stdin_open: true
    tty: true
    command: 
      - /bin/bash
      - -c
      - |
        /texpdf.sh principal



  ata:
    build:
      context: .
    volumes:
      - ../output:/output
      - ../tex:/tex
    stdin_open: true
    tty: true
    command: 
      - /bin/bash
      - -c
      - |
        /texpdf.sh ata
