services:

  principal:
    build:
      context: .
    volumes:
      - ../output:/output
      - ../tex:/tex
    stdin_open: true
    tty: true
    command: 
      - /bin/bash
      - -c
      - |
        ls -a .
        ls -a ..
        cat ../texpdf.sh 
        ../texpdf.sh principal



  ata:
    build:
      context: .
    volumes:
      - ../output:/output
      - ../tex:/tex
    stdin_open: true
    tty: true
    command: 
      - /bin/bash
      - -c
      - |
        ../texpdf.sh ata
